### ISSUE TITLE
[USER STORY 03] User Dashboard: Tasks/Homework

### ISSUE THREAD

**Issue by pixxelschubser** [pixxelschubser/capstone-project#3]

**Comment by pixxelschubser** [comment]
On the Dashboard the User is presented with a tile regarding his tasks/homework. The tile has a orange marker when any tasks deadline is set within the upcoming seven days and a red marker occurs when any tasks deadline is within the next two days.
Clicking on the Tile redirects the User onto a Task Page, where detailed information about his tasks are provided.

## Mock Up

## Acceptance Criteria
- [ ] The Dashboard displays a tasks tile
- [ ] The task tile redirects to a specified task page
- [ ] A "proximity marker" is displayed at the task tile to alert the User when any tasks are due soon.

## Tasks
- [ ] Create a Task Tile Component on the Dashboard
- [ ] Create a Task Page
- [ ] Implement redirect on click
- [ ] Implement redirect from Task Page to Dashboard
- [ ] Create a Marker Component
