### ISSUE TITLE
Front Page

### ISSUE THREAD

**Issue by pixxelschubser** [pixxelschubser/capstone-project#4]
As a User
I want to see the front page when I open the web app.

## Acceptance Criteria
- [x] The styled front page is visible upon page load

## Tasks
- [x] Set up the project
- [x] Create the front page
- [x] Add styling
