### ISSUE TITLE
Login: Show Password Toggle

### ISSUE THREAD

**Issue by lars-radtke** [pixxelschubser/capstone-project#5]
As a user
I need an option to show my password
so I can check on any typing errors

and I need the option to hide the password again
so it won't be displayed unprotected anymore.

## Mock Up

![Login-ShowPassword](https://user-images.githubusercontent.com/89029056/136852998-729ccfb9-8ca1-4e07-a26a-1ee77add57ff.jpg)

![Login-HidePassword](https://user-images.githubusercontent.com/89029056/136852985-63a33b43-29ec-4003-a7f4-db1926902759.jpg)

## Acceptance Criteria
- [ ] An icon button toggles a password shown/hidden state
- [ ] The button is accessible

## Tasks
- [ ] Create component tests
- [ ] Create toggle component
- [ ] create state variable
