### ISSUE TITLE
Log In

### ISSUE THREAD

**Issue by pixxelschubser** [pixxelschubser/capstone-project#6]
As a User
I need to log into the App
so only I can access my personal account.

## Mock Up

![Login](https://user-images.githubusercontent.com/89029056/136851967-f10d6b35-ba1d-4996-bf85-bd48984c2deb.jpg)

## Acceptance Criteria
- [x] The Log In Button contains an icon and text
- [x] The User is provided a form where he/she can enter his/her name and a password

## Tasks
- [x] Create tests
- [x] Create the Log in component
- [x] Add Styling
